spring:
  application:
    name: gateway-server
zuul:
  ignoredServices: '*'
  routes:
    application-service:
      path: /application-service/**
      serviceId: application-service
    hystrix:
      path: /hystrix/**
      serviceId: hystrix
    expense-service:
      path: /expense/**
      serviceId: expense-service
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka